### PR TITLE
Drop XPM icons from XDG icon theme

### PR DESCRIPTION
**Pull request by pinotree**
While XDG icon themes support XPM icons, PNG is supported and preferred. Hence, since PNG icons are available already, drop almost all the XPM variants.

The only icon not removed is the 32px version, which is built in the application; because of this, it is moved out of the directories with XDG icon theme icons, so it is not installed anymore.

### CODE REVIEW

**Comment by kartikm** [comment]
LGTM.

**Comment by rzvncj** [comment]
I'm not sure this is needed. Is there something that _doesn't_ work because those XPMs are there? Are you sure your use case is the only reasonable one (i.e. that some other platform doesn't prefer XPMs - or is perhaps unable to use the PNGs)?

I've only very recently stopped using WindowMaker myself, so I'm not a believer in the "old tech nobody uses" saying.

Long story short, unless you can provide a very good argument against the XPMs I see no harm in keeping them.

**Comment by pinotree** [comment]
According to the XDG icon theme specification [1]:

> An icon file is an image that can be loaded and used as an icon. The supported image file formats are PNG, XPM and SVG. PNG is the recommended bitmap format, and SVG is for vectorized icons. **XPM is supported due to backwards compability reasons, and it is not recommended that new themes use XPM files.** Support for SVGs is optional.

(emphasis is mine)

So it's very well possible for an implementation to not support XPM icons at all. Also, as data points:
- xchm already provides PNG icons for its application icon, so the vast majority (if not all) the loaders of XDG icon themes will load the PNG icon first (as it is to be found first), making the XPM icon effectively unused
- if I look at what is packaged in Debian, there is only a dozen packages that provide XPM versions of application icons installed as hicolor icon theme, and half of them have PNG variants as well. An XDG icon loader not supporting PNGs, other than being against the specs, it would already not support the very vast majority of icons out there, and in practice be useless.

This has nothing to do with "removing old tech just because it's old tech"; the hicolor XPM icons that xchm ships are effectively unused.

[1] https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

**Comment by rzvncj** [comment]
Fair enough. I still think WindowMaker (or similar-style window manager) users are not going to be happy about this - "obsolete" or not, last time I checked WindowMaker vastly preferred XPMs.

But I suppose this PR can be reverted if people complain.

Thanks, I'll merge and we'll see how it pans out.

**Comment by pinotree** [comment]
> I still think WindowMaker (or similar-style window manager) users are not going to be happy about this - "obsolete" or not, last time I checked WindowMaker vastly preferred XPMs.

As I mentioned: if WindowMaker does not support PNG icons for XDG icon theme, there is a bigger problem than a missing icon for xchm, as users do not see a lot of icons... If WindowMaker supports PNG icons (as it ought to for XDG icon theme), then this change is a no-op for them.

**Comment by rzvncj** [comment]
It's bigger than that, IIRC WindowMaker doesn't give a hoot about XDG at all. Your reasoning is XDG / Debian-centric.

**Comment by pinotree** [comment]
> It's bigger than that, IIRC WindowMaker doesn't give a hoot about XDG at all.

Then for them (or non-XDG icon theme users) whatever is installed in the hicolor icon theme, PNG or XPM, is not relevant, right? Which still makes this a no-op for them.

**Comment by rzvncj** [comment]
If WindowMaker is now happy with PNGs, then yes, they should be fine. I've merged your PR on this assumption (which may be false). It hasn't always been, I do remember cases where PNGs were ignored and XPMs were at least preferred, if not the only format supported between the two, for setting icons graphics for the WindowMaker right-side buttons. In fact, assuming that as single user has set one of those XPMs as the icon for a WindowMaker button, on upgrading to the xCHM version with your PR in it they will have to reconfigure their system. I'm not a fan of that line of thinking.

I'm still of the "if it ain't broke don't fix it" opinion in this case - I continue to not see what harm there was in keeping those poor XPMs and see no advantage in removing them, other than bragging rights in relation to the document you've quoted.

I also draw a different conclusion from the text you're quoting:
> XPM is supported due to backwards compability reasons, and it is not recommended that new themes use XPM files.

The keywords, to me, are "new", and "backwards compatibility". I like backwards compatibilty (which is what I was trying to say repeatedly), and this is not a _new_ theme, and simply removing those harmless XPMs (it is also a no-op to _not use them_ even though they're there, no? and we can't claim that there's much disk space saved by not having them) is just needless work.

It's easy to think that your system is the system everyone is using and your use-cases are valid for everyone else, but that's unfortunately almost never the case.

Then again, you've already done it, so we may as well use the effort, which is likely to work just fine.

**Comment by pinotree** [comment]
I understand your point of view of "not broken, do not change it". However, there are few points which I believe you did not consider:
- the affected icons are **only** for loaders of XDG icon themes: anything not loading XDG icon themes did not care about these icons _already_, so this change a no-op
- if WindowMaker is supporting XDG icon themes, then it ought to support PNGs already, as otherwise they won't show a lot of icons
- it does not matter what WindowMaker loads as non-XDG icon theme

> I like backwards compatibilty

Backward compatibility makes sense when there are use cases to support. As I explained already, this "backward compatibility" was effectively **useless**.

**Comment by pinotree** [comment]
> It's easy to think that your system is the system everyone is using and your use-cases are valid for everyone else, but that's unfortunately almost never the case.

Again, this has nothing to do with "my system" or "my use case". Please do not make it a personal matter, as it is definitely not the case. I went thought explanations in a logical way, please let's keep the discussion at that, thanks.

**Comment by rzvncj** [comment]
There's nothing personal about it, I'm sure that you'll see that if you reread our conversation. I was merely pointing out that you keep mentioning Debian and XDG, and while I respect your choices, I prefer Arch Linux and have used WindowMaker exclusively until a couple of years ago. Before that, I have used Slackware and Gentoo.

Some people use other window managers. I still write software mostly with Vim (the text-based version, in a console).

**Comment by pinotree** [comment]
> There's nothing personal about it, I'm sure that you'll see that if you reread our conversation.

You earlier sort of implied that I only considered what is in my system, or what is my own use case.

> I was merely pointing out that you keep mentioning Debian and XDG

Sigh. Is this really what you can get of my explanations?
- I mentioned XDG because these icons matter **only for XDG icon themes**; any other non-XDG icon is irrelevant to this discussion, and to these icons.
- I mentioned Debian only **once** (so the "keep repeating Debian" argument is nonsense), and only as data point of XPM icons in XDG hicolor icon themes in existing software. If there was easy way to check the content of all the packages in a bulk way in other distributions, I'd have checked them as well.

**Comment by rzvncj** [comment]
Here's what I mean about WindowMaker:

wmaker_xpms

My system does appear to now, at least, have PNG support for WindowMaker, but I can't know what systems xCHM will need to run on, or even if the users will use WindowMaker at all (at which point all bets are off). Having those XPMs in there hurt no one, and made sure that they _exist_ on a given system, whether XDG cares about them or not (hence an XDG-centric argument misses my point completely).

1. Assume somebody has already set an icon in WindowMaker to a previously installed XPM, and that XPM is now gone (after an xCHM upgrade) - even if said user's system supports the change to a PNG, we've now disrupted their workflow.
2. Assume somebody's system doesn't yet support PNGs for whatever activity they're doing with xCHM, and the XPM continue to be useful (regardless of XDG).
3. Consider people who package xCHM for distros, that now may have to update their scripts to remove the packaged XPMs.
3. You said no-ops are great, failing to consider that in this case the biggest no-op of them all would have been for us as developers to not have to go through creating, reviewing and discussing this PR, for users not to have to update their XPM icon to PNG because their XPM has disappeared on upgrade, and for package maintainers to not have to work to update their package-making scripts. And for XDG clients to just use the PNGs and ignore the XPMs.

Also, please note that none of the immediately apparent applications in that screenshot (aMule, audacity) were in any rush (or cared at all) to remove their delivered XPMs.

That's about all I have to say on this issue. I think the discussion is past being productive, and all this while I did, in spite of reservations that I did my best to explain, merge your PR.

**Comment by pinotree** [comment]
> whether XDG cares about them or not (hence an XDG-centric argument misses my point completely).

No, no, no, that's exactly the point: this change is **only** for consumers of XDG icons!

> Also, please note that none of the immediately apparent applications in that screenshot (aMule, audacity) were in any rush (or cared at all) to remove their delivered XPMs.

You still keep ignoring what I said, so let me repeat it once more:
- this change is relevant **only for XDG icon themes**
- other icons used by the application were not in the scope of my changes
- this change is **not** about XPM icons in general, for example what is used internally as data files

I still don't understand why you keep steering the discussion about XPM icons in general, which is **not** the case.

**Comment by rzvncj** [comment]
> No, no, no, that's exactly the point: this change is only for consumers of XDG icons!

But you have _removed_ almost all XPMs. They were placed in XDG-used directories, but were _optional_ for XDG use. _But_, WindowMaker could be made to use them as well, and they were very useful because depending on screen resolution you'd pick the 64x64 one, or the 128x128 one, etc.

In _completely removing_ all those XPMs from the repository, how are other consumers supposed to keep using them?

To put it another way: I was merely providing those XPMs to be friendly to older / alternative tech, as _optional_, and had to deliver them _somewhere_. The best choice seemed to be those directories, under the assumption that they're easiest to find there and that nothing will explode even if they're not being preferred.

By deleting them completely they become unavailable to alternative consumers. By putting them somewhere else, we just complicate issues for no good reason. By just keeping them as they were, we'd hurt nothing.

Now, it may indeed be time to drop those XPMs, I don't know. We'll know it wasn't if / when somebody reports an issue. That's pretty much all I was saying.

**Comment by pinotree** [comment]
> But you have removed almost all XPMs.

... installed in the hicolor XDG icon theme.

I did not remove the icons used in other ways, e.g. embedded in the application itself. If xchm had XPM installed in private locations (e.g. `$datadir/xchm`, `/usr/share/xchm` when typically installed with a `/usr` prefix), I'd have left them around.

> In completely removing all those XPMs from the repository, how are other consumers supposed to keep using them?

Again: we are talking about an XDG icon theme, so the proper and supported way to load these icons is with a loader of XDG icon theme. Directly loading the icons via their path without an XDG icon theme loader means your path can break with upgrades of whatever provides the icon, since there is no requirement for icons to be provided at certain sizes, or to be kept indefinitely.
For example, it is perfectly doable that a 22px icon is dropped, so the XDG icon theme loader will downscale a bigger icon (eg 48px) or even render an available SVG icon as 22px in case the loader supports SVG icons.

> In completely removing all those XPMs from the repository, how are other consumers supposed to keep using them?

If you want to load icons of an XDG icon theme (like the removed icons were), then use an XDG icon theme loader. This is the only supported way.

**Comment by rzvncj** [comment]
> If you want to load icons of an XDG icon theme (like the removed icons were), then use an XDG icon theme loader. This is the only supported way.

I continue to disagree, for reasons I believe were clearly outlined above. Unfortunately I don't have all day to argue about this, so will now close this discussion.

Thanks for the PR.

**Pull request merged**
